package modul10_tugas;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author pradigma
 */
public class BankKuHome extends javax.swing.JFrame {

    /**
     * Creates new form BankKuHome
     */
    public BankKuHome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // </editor-fold>                           
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logOut = new javax.swing.JButton();
        penarikan = new javax.swing.JButton();
        saldo = new javax.swing.JButton();
        setor = new javax.swing.JButton();
        transfer = new javax.swing.JButton();
        inputPenarikan = new javax.swing.JTextField();
        inputSetor = new javax.swing.JTextField();
        inputTransfer = new javax.swing.JTextField();
        inputPenarikan1 = new javax.swing.JTextField();
        inputPenarikan2 = new javax.swing.JTextField();
        keterangan = new javax.swing.JLabel();
        nilai = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        jLabel5.setText("jLabel5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setLayout(null);

        logOut.setBackground(new java.awt.Color(0, 51, 153));
        logOut.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        logOut.setText("LogOut");
        logOut.setBorder(null);
        logOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutActionPerformed(evt);
            }
        });
        jPanel1.add(logOut);
        logOut.setBounds(230, 440, 67, 23);

        penarikan.setBackground(new java.awt.Color(0, 51, 153));
        penarikan.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        penarikan.setText("Penarikan");
        penarikan.setBorder(null);
        penarikan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penarikanActionPerformed(evt);
            }
        });
        jPanel1.add(penarikan);
        penarikan.setBounds(50, 320, 100, 23);

        saldo.setBackground(new java.awt.Color(0, 51, 153));
        saldo.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        saldo.setText("Saldo");
        saldo.setBorder(null);
        saldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saldoActionPerformed(evt);
            }
        });
        jPanel1.add(saldo);
        saldo.setBounds(130, 220, 59, 23);

        setor.setBackground(new java.awt.Color(0, 51, 153));
        setor.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        setor.setText("Setor");
        setor.setBorder(null);
        setor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                setorActionPerformed(evt);
            }
        });
        jPanel1.add(setor);
        setor.setBounds(50, 380, 100, 17);

        transfer.setBackground(new java.awt.Color(0, 51, 153));
        transfer.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        transfer.setText("Transfer");
        transfer.setBorder(null);
        transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferActionPerformed(evt);
            }
        });
        jPanel1.add(transfer);
        transfer.setBounds(50, 350, 100, 20);

        inputPenarikan.setBackground(new java.awt.Color(153, 204, 255));
        inputPenarikan.setBorder(null);
        jPanel1.add(inputPenarikan);
        inputPenarikan.setBounds(160, 320, 120, 20);

        inputSetor.setBackground(new java.awt.Color(153, 204, 255));
        inputSetor.setBorder(null);
        jPanel1.add(inputSetor);
        inputSetor.setBounds(160, 380, 120, 20);

        inputTransfer.setBackground(new java.awt.Color(153, 204, 255));
        inputTransfer.setBorder(null);
        jPanel1.add(inputTransfer);
        inputTransfer.setBounds(160, 350, 120, 20);

        inputPenarikan1.setBackground(new java.awt.Color(153, 204, 255));
        inputPenarikan1.setBorder(null);
        jPanel1.add(inputPenarikan1);
        inputPenarikan1.setBounds(160, 320, 120, 20);

        inputPenarikan2.setBackground(new java.awt.Color(153, 204, 255));
        inputPenarikan2.setBorder(null);
        jPanel1.add(inputPenarikan2);
        inputPenarikan2.setBounds(160, 320, 120, 20);

        keterangan.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jPanel1.add(keterangan);
        keterangan.setBounds(20, 470, 240, 30);

        nilai.setFont(new java.awt.Font("Times New Roman", 3, 14)); // NOI18N
        jPanel1.add(nilai);
        nilai.setBounds(30, 440, 160, 30);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/modul10_tugas/y.jpeg"))); // NOI18N
        jLabel3.setText("jLabel3");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 310, 510);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 360, 520);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saldoActionPerformed
      int saldo = 200000;
        keterangan.setText("SISA SALDO YANG ANDA MILIKI");
        nilai.setText(""+saldo);
        // TODO add your handling code here:
    }//GEN-LAST:event_saldoActionPerformed

    private void penarikanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_penarikanActionPerformed
             String tarikan = inputPenarikan.getText();
            int saldo = 200000;
            int jmltarik = Integer.parseInt(tarikan);
            int total = saldo-jmltarik;
        nilai.setText(""+total);
        // TODO add your handling code here:
    }//GEN-LAST:event_penarikanActionPerformed

    private void transferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferActionPerformed
        String transfer = inputTransfer.getText();
        String saldolast = nilai.getText();
        nilai.setText(""+saldolast);
        int jmltransfer = Integer.parseInt(transfer);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo-jmltransfer;
        nilai.setText(""+total);
// TODO add your handling code here:
    }//GEN-LAST:event_transferActionPerformed

    private void setorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_setorActionPerformed
        String setor = inputSetor.getText();
        String saldolast = nilai.getText();
        nilai.setText(""+saldolast);
        int jmlsetor = Integer.parseInt(setor);
        int lastsaldo = Integer.parseInt(saldolast);
        int total = lastsaldo+jmlsetor;
        nilai.setText(""+total);
// TODO add your handling code here:
    }//GEN-LAST:event_setorActionPerformed

    private void logOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutActionPerformed
        new BankKuLogin().setVisible(true);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_logOutActionPerformed
/**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankKuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankKuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankKuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankKuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BankKuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BankKuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BankKuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BankKuHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BankKuHome().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField inputPenarikan;
    private javax.swing.JTextField inputPenarikan1;
    private javax.swing.JTextField inputPenarikan2;
    private javax.swing.JTextField inputSetor;
    private javax.swing.JTextField inputTransfer;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel keterangan;
    private javax.swing.JButton logOut;
    private javax.swing.JLabel nilai;
    private javax.swing.JButton penarikan;
    private javax.swing.JButton saldo;
    private javax.swing.JButton setor;
    private javax.swing.JButton transfer;
    // End of variables declaration//GEN-END:variables
}
